//Fetchers
export const FETCH_TRAIN_TRIPS          = 'FETCH_TRAIN_TRIPS';
export const FETCH_TRAIN_ROUTES         = 'FETCH_TRAIN_ROUTES';
export const FETCH_TRAIN_STOPS          = 'FETCH_TRAIN_STOPS';
export const FETCH_GOOGLE_MAPS_API_KEY  = 'FETCH_GOOGLE_MAPS_API_KEY';

//Finders
export const FIND_SELECTED_TRAIN_ROUTE = 'FIND_SELECTED_TRAIN_ROUTE';
export const FIND_TIME_STAMP = 'FIND_CURRENT_TIME_STAMP';

//Setters
export const SET_TRAIN_ROUTE_DIRECTION  = 'SET_TRAIN_ROUTE_DIRECTION';
export const SET_CLOCK_TIME = 'SET_CLOCK_TIME';